image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

job:
  backoffLimit: 2
  ttlSecondsAfterFinished: 300

resources:
  requests:
    cpu: 50m
    memory: 64Mi

nameOverride: ""
fullnameOverride: ""
